[tool.poetry]
name = "cyberdata"
version = "0.1.5"
description = "Joe Zhou"
authors = ["Joe Zhou", "Tim Wang"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.2"
python-dotenv = "^1.1.0"
openai = "^1.68.2"
pyyaml = "^6.0.2"
ipykernel = "^6.29.5"
langchain = "^0.3.22"
pandas = "^2.2.3"
langchain-community = "^0.3.23"
langchain-openai = "^0.3.14"
scikit-learn = "^1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
