[tool.poetry]
name = "cyberdata"
version = "0.1.5"
description = "Joe Zhou"
authors = ["Joe Zhou", "Tim Wang"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.2"
python-dotenv = "^1.1.0"
openai = "^1.68.2"
pyyaml = "^6.0.2"
ipykernel = "^6.29.5"
langchain = "^0.3.22"
pandas = "^2.2.3"
langchain-community = "^0.3.23"
langchain-openai = "^0.3.14"
scikit-learn = "^1.7.0"
bs4 = "^0.0.2"
xgboost = "^3.0.2"
plotly = "^6.2.0"
torch = "^2.7.1"
torchvision = "^0.22.1"
torchaudio = "^2.7.1"
transformers = {extras = ["torch"], version = "^4.53.0"}
nbformat = "^5.10.4"
huggingface-hub = {extras = ["hf-xet"], version = "^0.33.2"}
sentence-transformers = "^5.0.0"
bertopic = "^0.17.0"
umap-learn = "^0.5.9.post2"
loguru = "^0.7.3"
anthropic = "^0.68.1"
google-generativeai = "^0.8.5"
statsmodels = "^0.14.5"
scipy = "^1.16.2"
matplotlib = "^3.10.6"
seaborn = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
