[tool.poetry]
name = "cyberdata"
version = "0.1.5"
description = "Joe Zhou"
authors = ["Joe Zhou", "Tim Wang"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.2"
python-dotenv = "^1.1.0"
openai = "^1.68.2"
pyyaml = "^6.0.2"
ipykernel = "^6.29.5"
langchain = "^0.3.22"
pandas = "^2.2.3"
langchain-community = "^0.3.23"
langchain-openai = "^0.3.14"
scikit-learn = "^1.7.0"
bs4 = "^0.0.2"
xgboost = "^3.0.2"
nltk = "^3.9.1"
umap-learn = "^0.5.7"
plotly = "^6.1.2"
nbformat = "^5.10.4"
torch = "^2.7.1"
torchvision = "^0.22.1"
torchaudio = "^2.7.1"
transformers = "^4.52.4"
sentence-transformers = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
